### ISSUE TITLE
Gnome 3.32

### ISSUE THREAD

**Issue by Sidethorn** [bananenfisch/RecentItems#7]
Hello I don't get any error but it doesn't show on tray. thank you.

**Comment by bananenfisch** [comment]
Is the extension active? (check in gnome-tweaks)
Or any error messages in journalctl?

**Comment by Sidethorn** [comment]
the extension is active and no error showed up in journalctl

**Comment by gnumanx** [comment]
> Hello I don't get any error but it doesn't show on tray. thank you.

Here the same.

**Comment by sxc731** [comment]
Same issue here (Stock Ubuntu 19.04, just upgraded from 18.10 which had RecentItems installed and working).  It's definitely enabled in GNOME Tweaks but doesn't appear on the tray.

Is there a way we can contribute to debugging the issue?  I looked at `syslog` and `journalctl`'s output to no avail.  Many thanks!

**Comment by bananenfisch** [comment]
it seems, the original ES6 version from demokritos was right - and my code cleaning was missing a point. since i am still on 3.20 with debian unstable, i cannot reproduce, but version 17 should now work with gnome 3.32.
can you try version 17: https://github.com/bananenfisch/RecentItems/releases/tag/17
... and give me a feedback please.
thx!

**Comment by Sidethorn** [comment]
Hi there, v17 works perfectly good! thanks for the quick answering and fix!

**Comment by bananenfisch** [comment]
Thanks for testing! Will push v17 to gnome.extensions.org.
